# Generated by Django 4.0.4 on 2022-04-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='make',
            field=models.CharField(default='Stellantis', max_length=120),
        ),
        migrations.AlterField(
            model_name='driver',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
