# Generated by Django 4.0.4 on 2022-04-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar', '0002_alter_driver_make_alter_driver_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=120)),
                ('speed', models.DecimalField(decimal_places=15, max_digits=30)),
                ('speedlimit', models.DecimalField(decimal_places=15, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
