# Generated by Django 4.0.4 on 2022-04-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellar', '0003_vehicledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='latitude',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='longitude',
            field=models.CharField(max_length=120),
        ),
    ]
